name: Auto-build doxygen docs
on:
  push:
    branches:
      - master
   
  
  
jobs:  
  doxygen:
    permissions:
       contents: write    
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        show-progress: ''
    - name: Setup and run doxygen
      run: sudo apt update && sudo apt install doxygen graphviz qhelpgenerator-qt5 -y
    - name: Set up Git LFS
      run: |
          git lfs install
          git lfs track "*.qch"  
    - name: Run doxygen
      run: doxygen Doxyfile
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.MR_TOKEN }}
        commit-message: update QCH file
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        title: Update QCH Help file
        body: |
         - Updating QT Help file following commit ${{ github.sha }}.
         - Auto-generated by [create-pull-request][1]

         [1]: https://github.com/peter-evans/create-pull-request
        branch: update-qch
        labels: | 
          qch
          cicd
        delete-branch: true
        add-paths: doc/*.qch
    - uses: actions/upload-pages-artifact@v3
      with: 
       path: ${{ github.workspace }}/doc/html/
  deploy:
    # Add a dependency to the build job
    needs: doxygen

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
